FROM python:3.5.1
ENV PYTHONUNBUFFERED 1
RUN apt-get update && \
    apt-get install -y netcat --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*
RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install -r requirements.txt
ADD . /code/
